// <auto-generated />
namespace HospiceWebPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class remove_model_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_model_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201503150507085_remove_model_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
