// <auto-generated />
namespace HospiceWebPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class resource_meetings_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resource_meetings_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201503132231206_resource_meetings_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
